### ISSUE TITLE
Data fields

### ISSUE THREAD

**Issue by jpolka** [transpose-publishing/policies-database#1]
**2018-05-08 update: Please see [this comment](https://github.com/transpose-publishing/policies-database/issues/1#issuecomment-387247838) for a revised architecture and list of data fields.**

For each journal record, we hope to assemble the following fields (draft; please edit):

### Journal information
- Journal title (from SHERPA/RoMEO: jtitle)
- Journal ISSN (from SHERPA/RoMEO: issn)
- Publisher (from SHERPA/RoMEO: romeopub)
- Date SHERPA/RoMEO information was last updated (from SHERPA/RoMEO: dateupdated)

#### Open Peer Review
- Peer review policy url
- Does the journal publish the content of peer reviews? (mandatory/optional/no)
- Are reviewer identities revealed to the author? (mandatory/optional/no)
- Are reviewer identities published? (mandatory/optional/no)

#### Co-reviewers
- Co-reviewer policy url
- Journal’s policy about co-reviewers (people who collaborate with an invited reviewer) (free text)
- Does the journal make it clear in the invite email that co-reviewers can contribute? (yes/no)
- Is there a dedicated place in the submission form to identify co-reviewers? (yes/no) 

#### (NEW suggestion) Peer review transfer
- Transfer policy url
- Policy on transfer of peer reviews
- What is the structure of the review form (are there separate fields for technical & impact evaluation?)

#### (NEW suggestion after conversation with B. Konforti) Peer review credit
- Does the journal deposit peer review information into ORCiD? [info](https://orcid.org/blog/2017/09/15/peer-review-orcid-community)

### Preprints
- Preprint policy url
- Are preprints allowed? (from SHERPA/RoMEO: prearchiving) (can/cannot/restricted/unclear)
- Preprint restrictions (from SHERPA/RoMEO: prerestrictions)
- Copyright policy url (from SHERPA/RoMEO: copyrighturl)
- Conditions (from SHERPA/RoMEO: conditions)
- Version of the preprint that can be posted to a disciplinary server (first submission only, any, other, none)
- Time when a preprint can be posted (before acceptance only, anytime, other)
- Acceptable servers (or characteristics) of servers (specific names, non-commercial, “recognized, etc)
- Media policy on preprints (what type of coverage or discussion (scientific blog, etc) of preprints is allowed?) (free text)
- Policies on preprint licensing (recommended or restricted licenses (eg, CC etc) for preprints) (free text)
- “Scoop protection” policy (ie, submitted preprints will not be rejected if a competing work comes out in another journal after the date of preprinting) (free text)
- Preprint citation policy (can preprints be cited in the reference list? Is there a special format?) (free text)
- Policy on incorporating community reviews or comments on preprints into editorial assessment (free text)

All data from SHERPA RoMEO is released under a CC BY-NC-SA 2.5 license and we will follow the [specified conditions for reuse](http://www.sherpa.ac.uk/romeoreuse.html).

**Comment by tonyR-H** [comment]
For peer review, add

- Peer review policy url

**Comment by jpolka** [comment]
Done @tonyR-H - also proposed sections on peer review transfer - one question could come from the policy, but the question about structure could be collected in the same way as the one about whether there is a space in the form for co-reviewers.

**Comment by dhimmel** [comment]
The outline of the data fields is useful. There are two aspects I think we want to decide on before getting started.

First, **what catalog of journals to use**. This is important because the resource we choose here will define what journals are in the database. Currently, the plan appears to be to use RoMEO journals. Other options would be [Crossref](https://github.com/greenelab/crossref) or [Scopus](https://github.com/dhimmel/scopus). Crossref is probably best IMO, as it seems to be the longterm provider for this type of information that the community is coalescing behind. They also claim no copyright on the metadata. Compared to Scopus, Crossref is more dependent on publishers depositing information, which can lead to issues, but the DOI system has already matured quite a bit and things are improving. Using ISSNs we can map journals between resources as well.

Second, **is there an architecture where we can release the data we create as CC0?** Under the current plan, will we be required to release the data we create under a CC BY-NC-SA license (because of share alike)? If so, I think that is highly undesirable. If we are going to put in the time, it'd be nice to contribute to an open ecosystem rather than grow a closed one. One option would be separate the original data we collect from RoMEO data. We could then combine the two into a CC BY-NC-SA resource as needed, but the raw data we create will remain unencumbered. This would be a natural workflow even were we to use Crossref to identify journals.

So both issues really relate to how central RoMEO will be in this effort. I see why it makes sense to simply extend RoMEO from a convenience perspective and due to the overlap in scope. However, the licensing issues are worrisome. In addition, I am not sure how RoMEO manages its journal database and whether it will be as reliable as Crossref's catalog going forward. Apologies for derailing the focus of this issue :smirk_cat:

**Comment by dhimmel** [comment]
> journals are mapped to not only publishers but also groups of journals (for example, Cell takes its policies from the Cell Press policies, not its parent, Elsevier).

Cool! So RoMEO includes an ontology of publishing entities. And the curators job here will be to annotate entities with policies. Each entity would have a YAML file, and we would apply policies to the highest-level entity to which a policy applies (i.e. Cell Press not Cell). When displaying the information, we can make subentities inherit the policies of superentities (by propagating policies down the acyclic directed graph). Assuming that the ontology data is readily available and that RoMEO maintains this resource, I agree it will be preferable to Crossref.

> it would be great to be able to make sure that SHERPA RoMEO or other parties could display some of the information we collect along with RoMEO data

Certainly! I'd like our work to be CC0 so anyone can reuse this information without having to worry about legal impediments. Hopefully, we can make it quite easy for other projects to integrate our data, so RoMEO, Wikidata & others can help broadcast this information. The main question is what architectures will permit us to openly release our work, given that RoMEO data is released under [CC BY-NC-SA 2.5](https://creativecommons.org/licenses/by-nc-sa/2.5/legalcode)? The important aspects of the license deed are the defition of "derivative work":

> "Derivative Work" means a work based upon the Work or upon the Work and other pre-existing works, such as a translation, musical arrangement, dramatization, fictionalization, motion picture version, sound recording, art reproduction, abridgment, condensation, or any other form in which the Work may be recast, transformed, or adapted, except that a work that constitutes a Collective Work will not be considered a Derivative Work for the purpose of this License.

In addition, here is the share alike stipulation:

> You may distribute, publicly display, publicly perform, or publicly digitally perform a Derivative Work only under the terms of this License, a later version of this License with the same License Elements as this License, or a Creative Commons iCommons license that contains the same License Elements as this License (e.g. Attribution-NonCommercial-ShareAlike 2.5 Japan).

How I understand these clauses and copyright law is that any files that include RoMEO data may be derivatives and trigger Share Alike. However, files that don't contain RoMEO data but that were computed using RoMEO data wouldn't trigger Share Alike. Hence, we can use the RoMEO ontology to propagate policy annotations without having to share alike the resulting outputs. However, we will need each source YAML file to contain at least the RoMEO entity ID. Perhaps SHERPA would be willing to allow us to use the journal IDs and names in a CC0 resource. This would be similar to the licensing approach DrugBank adopted where basic drug information and identifiers are CC0 with the detailed data under a non-commerical license. This allows using the resource's identifiers without viral licensing issues.

So I think we should ask SHERPA if we can release files with journal/publisher IDs as CC0. Under this proposal, files that contained preprint links or other relationships from RoMEO would still be CC BY-NC-SA. However, our source files would be CC0 opening up the possibility for unrestricted reuse to users who do not need the RoMEO aspects of the data.

If we cannot use RoMEO IDs under CC0, then our choices would be to consider fair use or to consider replicating SHERPA's journal ontology efforts to create an openly-licensed resource. I think duplicating these efforts would be considerably worse for both us and SHERPA, so hopefully we avoid that route.

**Comment by jpolka** [comment]
Daniel, do you know how similar the ISSNs in Crossref and SHERPA are? (a list is available w/our API key at http://www.sherpa.ac.uk/downloads/) If they are similar, I assume we could match journals to entities via Crossref ISSNs.

This isn't a given, though: in Wikidata, some journal have many ISSNs (print and electronic versions have separate ISSN - in SHERPA the latter are called ESSNs, I believe) and there can be multiples of each (presumably if a journal changes publishers?)

**Comment by jpolka** [comment]
Seeing your Crossref issue, could we also do this matching with journal names?

**Comment by dhimmel** [comment]
> could we also do this matching with journal names?

We should avoid automated mapping by names at all costs. The different databases will likely use different names for the same journals. If we do need to map journals by names, we will need to manually review each mapping (and consider whether we can contribute information so the mapping can be done automatically in the future).

BTW in the past, I've mapped Crossref DOIs (articles) to journals using ISSNs, so I know they have this information (at least for specific articles).

**Comment by jpolka** [comment]
While the Crossref API issue gets sorted, a .csv of Crossref journals with print and electronic ISSNs can be found here: https://support.crossref.org/hc/en-us/articles/213197226-Browsable-title-list

**Comment by SamanthaHindle** [comment]
Hey @jpolka 
I added one point above 
"- Does the journal make it clear in the invite email that co-reviewers can contribute? (yes/no)"

I realized afterwards that I probably should have listed it here instead. Feel free to remove or edit it.

I'm glad to see the inclusion of the journal's policy on incorporating community reviews into peer review 😁 ❤️

**Comment by jpolka** [comment]
Great @SamanthaHindle - thank you! I also updated the text to include the following:

#### (NEW suggestion after conversation with B. Konforti) Peer review credit
- Does the journal deposit peer review information into ORCiD? [info](https://orcid.org/blog/2017/09/15/peer-review-orcid-community)

**Comment by jpolka** [comment]
Following a conversation with @dhimmel, we will have one YAML file per romeopub (policy ID from SHERPA/RoMEO). 

We will make it clear to contributors that their contributions are licensed CC0. However, the policy files will be licensed CC BY-NC-SA 2.5 because they contain SHERPA RoMEO information. We will follow the [specified conditions for reuse](http://www.sherpa.ac.uk/romeoreuse.html). 

Here is a revised list of data fields. @SamanthaHindle, @tonyR-H  and @garymcdowell - let me know what you think? Specifically, if we collect the urls, do we need the "journal's policy about" fields, which may be very long/unwieldy?

Furthermore, after a conversation with Monica Gradanos/
--------

**Suggested labels for the YAML file** are bolded. Comments follow. (Allowed responses for validation in parentheses - these should also be visible in the comments.)

**romeopub** Policy ID from SHERPA/RoMEO
**journals** A list of the journals from SHERPA/RoMEO associated with this romeopub (jtitle) 

_These fields should probably not be editable, but we should provide a way to flag the entry if the journals listed are not all affected by the same policies_

### Peer review
#### Open Peer Review
- **peer-review-url** Peer review policy url (valid url)
- **open-reports** Does the journal publish the content of peer reviews? (mandatory/optional/no)
- **identities-revealed** Are reviewer identities revealed to the author? (mandatory/optional/no)
- **identities-published** Are reviewer identities published? (mandatory/optional/no)

#### Co-reviewers
- **co-review-url** Co-reviewer policy url (valid url)
- **co-review-policy** Journal’s policy about co-reviewers - ie people who collaborate with an invited reviewer (free text)
- **co-review-invited** Does the journal make it clear in the reviewer invitation email that co-reviewers can contribute? (yes/no)
- **co-review-field** Is there a dedicated place in the submission form to identify co-reviewers? (yes/no) 

#### Peer review transfer
- **transfer-url** Transfer policy url (valid url)
- **transfer-policy** Policy on transfer of peer reviews (free text)
- **review-structure** What the titles of the sections of the review form? (free text)
- **separate-structure** Are there separate fields for technical & impact evaluation? (yes/no)

#### Peer review credit
- **credit-url** Peer review credit policy url (valid url)
- **orcid** Does the journal deposit peer review information into ORCiD? "via service" includes Publons. (directly/via service/no)

### Preprints
- **preprint-url** Preprint policy url (valid url)
- **preprint-version** Version of the preprint that can be posted to a disciplinary server (first submission only, any, other, none)
- **preprint-time** Time when a preprint can be posted (before acceptance only, anytime, other)
- **preprint-citation** Can preprints be cited in the reference list? (yes/no)
- **acceptable-servers** Acceptable servers or characteristics of servers - eg specific names, non-commercial, “recognized," etc (free text)
- **preprint-media** What type of coverage or discussion of preprints is allowed, eg in the media or in scientific blogs? (free text)
- **preprint-licensing** Policies on preprint licensing (free text)
- **scoop-protection** Policy on whether submitted preprints will not be rejected if a competing work comes out in another journal after the date of preprinting (free text)
- **community-reviews** Policy on incorporating community reviews or comments on preprints into editorial assessment (free text)
