### ISSUE TITLE
Journals associated with more than one policy

### ISSUE THREAD

**Issue by jpolka2** [transpose-publishing/policies-database#25]
BMJ appears in both [romeo_1174](https://github.com/transpose-publishing/policies-database/blob/master/policies/policies/romeo_1174.yml) and [romeo_25](https://github.com/transpose-publishing/policies-database/blob/master/policies/policies/romeo_25.yml) which is its parent. At some point we may want to propagate missing info in the child policy from the parent policy and remove duplicate journals from the parent policies, in order to simplify the display.

**Comment by jpolka** [comment]
Will do - great idea!

**Comment by dhimmel** [comment]
I'm reopening this issue and we'll automatically close it when the journals field is split in production!
